coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 1%
        informational: false
    project:
      default:
        informational: true
  
  ignore:
    - "tests/"
    - "docs/"
    - "scripts/"
    - "examples/"
    - "*.lock"
    - "*.bundle"
    - ".pixi/"
    - ".omnibenchmark/"
    - "build/"
    - "dist/"
    - "htmlcov/"
    - "*.yaml"
    - "*.yml"
    - "*.toml"
    - "*.cfg"
    - "*.ini"
    - "CHANGELOG.md"
    - "README.md"
    - "LICENSE"
    - "requirements.txt"

  range: 50..100
  round: down
  precision: 2
