#!/usr/bin/env snakemake -s

import shutil
import os
import os.path as op

# TODO: No idea where this import comes from.
# from env_modules_python import module

from omnibenchmark.software import easybuild_backend as easy
from omnibenchmark.software import common

LMOD_VERS="8.7"

easyconfigs = ['binutils-2.35.eb']

WD = 'testing_04'

rule all:
    input:
        op.join('binutils-2.35.eb_ld.txt')

os.makedirs(WD, exist_ok = True)

for eb in easyconfigs:
    rule:
        name: f"{{easyconfig}}_easybuild_build".format(easyconfig=eb)
        wildcard_constraints:
            easyconfig=eb
        output:
            flag = op.join(WD, '{easyconfig}_flag')
        log:
            log = op.join(WD, 'install_{easyconfig}.log')
        params:
            workdir = WD
        run:
            with open(log.log, 'w') as logtxt:
                # print(module('list'))
                common.check_easybuild_status()
                ret = easy.easybuild_easyconfig(easyconfig = eb,
                                                threads = 2)
                if (ret.returncode == 0):
                    logtxt.write(ret.stdout)
                    logtxt.write(ret.stderr)
                    with open(output.flag, 'a'):
                        os.utime(output.flag, None)

    rule:
        name: f"{{easyconfig}}_test".format(easyconfig=eb)
        wildcard_constraints:
            easyconfig = eb
        input:
            flag = op.join(WD, '{easyconfig}_flag')
        envmodules:
            #op.join('all', easy.get_envmodule_name_from_easyconfig(eb))
            easy.get_envmodule_name_from_easyconfig(eb)
        params:
            env = easy.get_envmodule_name_from_easyconfig(eb)
        output:
            op.join('{easyconfig}_ld.txt')
        shell:
            """
            # module spider
            ld --version > {output}
            """
