#!/usr/bin/env snakemake -s
##
## Handles (installs) the software stack to run a benchmark, including modules/easybuild themselves
##
## Izaskun Mallona 27 May 2024

# re: environments
# https://stackoverflow.com/questions/44316075/using-pyenv-in-a-snakemake-rule

import glob
import re
import os
import os.path as op
from shutil import which
from easybuild_backend import *
from conda_backend import *

WD = op.join('soft')
#MODULEPATH="$HOME/.local/easybuild/modules/all/"
HOME=op.expanduser("~")
LMOD_VERS="8.7"
## use half of the available cores
NTHREADS = int(len(os.sched_getaffinity(0)))/2

export_lmod_env_vars()

for p in [op.join(WD, 'recipes'), op.join(WD, 'images')]:
    if not op.exists(p):
        os.makedirs(p)

# mind the shell prefix
# shell.prefix("set -o pipefail; ")

easyconfigs=['R-4.3.3-gfbf-2023b.eb', 'Bowtie2-2.4.4-GCC-11.2.0.eb', 'PyInstaller-6.3.0-GCCcore-12.3.0.eb']
# easyconfigs= ['zfp-0.5.5-GCCcore-10.2.0.eb']
# easyconfigs = ['binutils-2.35.eb']

rule all:
    input:
        expand(op.join(WD, 'recipes', 'Singularity_{eb}.txt'), eb = easyconfigs)

# not needed, sing-only now
rule install_lmod:
    output:
        lmod = op.join(HOME, 'soft', 'lmod', LMOD_VERS, 'libexec', 'lmod')
    log:
        op.join(WD, 'lmod.log')
    params:
        path = WD
    run:
        if check_module_tool() == 1:
            install_lmod()

# toolchain = 'GCCcore-10.2.0'

for eb in easyconfigs:
    envmodule_name = get_envmodule_name_from_easyconfig(eb, workdir = WD)
    rule:
        name: f"{{easyconfig}}_config".format(easyconfig=eb)
        wildcard_constraints:
            easyconfig=eb
        input:
            lmod = op.join(HOME, 'soft', 'lmod', 'lmod')
        output:
            singularity_recipe = op.join(WD, 'recipes', 'Singularity_{easyconfig}.txt'),
            container = op.join(WD, 'images', '{easyconfig}' + '.sif')
        log:
            op.join(WD, 'Singularity_{easyconfig}.log')
        params:
            workdir = WD,
            LMOD_VERS = LMOD_VERS
        threads:
            NTHREADS
        run:
            # largely from https://github.com/sassy-crick/Singularity-Easybuild        
            create_definition_file(easyconfig = eb, singularity_recipe = output.singularity_recipe,
                                   envmodule = envmodule_name, nthreads = str(int(NTHREADS)))
            ## fakeroot, no sandbox
            shell("""
            export PATH=/usr/sbin:$PATH
            singularity build \
               --fakeroot \
               {output.container} \
               {output.singularity_recipe} &> {log}""")
