name: Code Style Check

on:
  pull_request:

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Linters
        run: pip install ruff

      # Ruff check
      - name: Lint with Ruff
        continue-on-error: false
        run: |
          ruff check .
