name: Publish mkdocs via GitHub Pages
on:
  workflow_dispatch: # Allow manual trigger if needed

jobs:
  build:
    name: Render and deploy docs via mkdocs
    runs-on: ubuntu-latest
    steps:
      - name: Install sys deps
        run: |
          sudo apt update && sudo apt install -y bibtool  \
            software-properties-common wget \
            python3-dev \
            python3-pip \
            git \
            build-essential

          python --version
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: omnibenchmark.org
          CONFIG_FILE: docs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt
        run: |
            pip install -r docs/requirements.txt

            echo "${CUSTOM_DOMAIN}" > "${GITHUB_WORKSPACE}/docs/CNAME"

            remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"

            if ! git config --get user.name; then
              git config --global user.name "${GITHUB_ACTOR}"
            fi

            if ! git config --get user.email; then
              git config --global user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"
            fi

            git remote rm origin
            git remote add origin "${remote_repo}"
            
            mkdocs gh-deploy --config-file "${CONFIG_FILE}" --force --theme material
